server:
  port: 9876
logging:
  file:
    name: logs/mywallpapermgr.log
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:file:~/h2/mywallpapermgr;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

endpoints:
  shutdown:
    enabled: true